# Generated by Django 2.2.12 on 2023-03-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companemployee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personne',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='personne',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
