# Generated by Django 2.2.12 on 2023-03-15 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companemployee', '0002_auto_20230315_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salaire',
        ),
        migrations.AddField(
            model_name='employee',
            name='hiring_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date hired'),
            preserve_default=False,
        ),
    ]
